name: Prerelease

on:
  push:
    tags:
      - "mysoftware/v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Create GitHub Pre-Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create --draft --verify-tag --generate-notes --title "${GITHUB_REF_NAME}" "${GITHUB_REF_NAME}"

      - name: Upload artifacts
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo aaaa > hello.txt
          gh release upload "${GITHUB_REF_NAME}" hello.txt
