name: Prerelease

on:
  push:
    tags:
      - "mysoftware/v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository != 'zgtm/mysoftware'
    steps:
      - uses: actions/checkout@v6

      - run: echo hi
