name: Release
### NOTE: This pipeline needs a secret REPO_TOKEN with workflow scope in order to push merged workflow files to the new repository

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository != 'zgtm/mysoftware' &&
        (github.event_name != 'release' || !github.event.release.draft)
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v6

      - run: |
          echo "hellllooo"
