name: Release

on:
  release:
    types: [published, edited released]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ !github.event.release.prerelease }}
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v6
        with:
          path: source

      - name: Checkout target repository
        uses: actions/checkout@v6
        with:
          repository: zgtm/mysoftware
          token: ${{ secrets.REPO_TOKEN }}
          path: target

      - name: Merge repositories
        run: |
          cd target
          git remote add source ../source
          #git fetch source
          git fetch --unshallow source refs/tags/$GITHUB_REF_NAME:refs/tags/$GITHUB_REF_NAME
          git merge source/$GITHUB_REF_NAME
          git push

      - name: Create release in another repo
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          gh release create --repo zgtm/mysoftware --generate-notes "${GITHUB_REF_NAME}"
