name: Release
### NOTE: This pipeline needs a secret REPO_TOKEN with workflow scope in order to push merged workflow files to the new repository

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository != 'zgtm/mysoftware' &&
        (github.event_name != 'release' || !github.event.release.draft)
    steps:
      - name: Strip release-candidate suffix for release version
        run: |
          echo "VERSION_BASE=${GITHUB_REF_NAME%%-*}" >> "$GITHUB_ENV"

      - name: Checkout source repository
        uses: actions/checkout@v6
        with:
          path: source
          fetch-depth: 0 # Needed to merge histories

      - name: Checkout target repository
        uses: actions/checkout@v6
        with:
          repository: zgtm/mysoftware
          token: ${{ secrets.REPO_TOKEN }}
          path: target
          fetch-depth: 0 # Needed to merge histories

      - name: Merge repositories
        run: |
          cd target
          git remote add source ../source
          git fetch source refs/tags/$GITHUB_REF_NAME:refs/tags/$GITHUB_REF_NAME
          git config user.email "releases@peeriot.io"
          git config user.name "Peeriot Release Pipeline"
          git merge $GITHUB_REF_NAME
          git push

      - name: Create release in another repo
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          gh release create --repo zgtm/mysoftware --generate-notes "${VERSION_BASE}"


      - name: Download and reupload artifacts
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          mkdir assets
          gh release download --repo zgtm/testrelease "${VERSION_BASE}" --dir assets
          gh release upload --repo zgtm/mysoftware "${VERSION_BASE}" assets/*
